[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
